In [4]:
import numpy as np
import gym
import random
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17283034491138262617
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 1456957030
locality {
  bus_id: 1
  links {
  }
}
incarnation: 10486244426690451907
physical_device_desc: "device: 0, name: Quadro M600M, pci bus id: 0000:01:00.0, compute capability: 5.0"
]


In [2]:
from gym.envs.registration import register
register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '8x8', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.8196, # optimum = .8196, changing this seems have no influence
)


In [4]:
env = gym.make("FrozenLake-v0")
env.reset()                    
env.render()

c:\users\ani\gym\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)



SFFF
FHFH
FFFH
HFFG


c:\users\ani\gym\gym\__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')


In [5]:
action_size, state_size = env.action_space.n, env.observation_space.n

In [6]:
qtable = np.zeros((state_size,action_size))

In [7]:
total_episodes = 15000
total_test_episodes = 100
max_steps = 99
lr = 0.8
gamma = 0.95
epsilon = 1.0
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.005

In [11]:
rewards = []

for episode in range(total_episodes):
  
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        
        random_num = random.uniform(0,1)

        if random_num > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + lr * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        state = new_state
        total_rewards +=reward

        if done==True:
            break

    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.47673333333333334
[[1.18032246e-01 3.75587378e-02 2.34486911e-02 3.31616612e-02]
 [3.53611324e-03 3.35975682e-03 4.62032815e-03 4.44754991e-02]
 [4.95863880e-03 1.01713102e-02 5.52135122e-03 1.00841409e-02]
 [5.55616909e-04 3.10993961e-03 1.13554173e-04 9.74035710e-03]
 [1.43251885e-01 9.64022669e-03 9.64228029e-03 1.06607287e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.03637838e-06 9.40733680e-06 5.95509918e-04 6.08941033e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.13167410e-02 3.28321198e-03 3.16716136e-02 1.35715009e-01]
 [1.58943535e-02 4.14295553e-01 1.15397632e-02 3.88924244e-03]
 [3.25727975e-01 2.64295823e-04 1.56739523e-04 7.96935351e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.69806389e-03 8.64040531e-03 7.52706146e-01 4.67847928e-03]
 [1.24811061e-01 3.83370881e-01 9.75338986e-01 2.48321746e-01]
 [0.00000000e+00 0

In [12]:
for episode in range(total_test_episodes):
    state = env.reset()
    total_reward = 0
    step = 0
    done = False
  
    for step in range(max_steps):
        new_state, reward, done, info = env.step(action)
        total_reward += reward

        if done:
            env.render()
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))

  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
